export enum WSClientEvent {
  SEND_PEER_MESSAGE = 'SEND_PEER_MESSAGE',
  SEND_GROUP_MESSAGE = 'SEND_GROUP_MESSAGE',
  RECEIVE_MESSAGE = 'RECEIVE_MESSAGE',
  READ_MESSAGE = 'READ_MESSAGE',
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
}
