export enum WSServerEvent {
  // MESSAGE_DELIVERD="MESSAGE_DELIVERD",
  // MESSAGE_READ="MESSAGE_READ",

  NEW_MESSAGE = 'NEW_MESSAGE',
  NEW_PEER_CHANNEL = 'NEW_PEER_CHANNEL',
  NEW_GROUP_CHANNEL = 'NEW_GROUP_CHANNEL',
  NEW_GROUP_CHANNEL_MEMBERS = 'NEW_GROUP_CHANNEL_MEMBERS',
}